services:
  postgres_db:
    image: postgres:15
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=users_db      # Название базы данных
      - POSTGRES_USER=admin       # Логин админа
      - POSTGRES_PASSWORD=secret  # Пароль админа
    ports:
      - "5432:5432"
    networks:
      - prisma-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d users_db" ]
      interval: 5s
      timeout: 2s
      retries: 20
    # Добавляем том для хранения данных
    volumes:
      - postgres_volumes:/var/lib/postgresql/data  # Стандартная папка данных PostgreSQL

  # Сервер на Express
  api:
    build: .
    container_name: api
    ports:
      - '3000:3000' # Express-сервер будет доступен на 3000 порту
    # Команда запуска (выполняется после сборки)
    command: sh -c "npx prisma migrate deploy && node dist/index.js"  # Миграции + запуск сервера
    # Зависимости между сервисами
    depends_on:
      postgres_db:
        condition: service_healthy  # Ждем успешного healthcheck БД
    env_file:
      - .env.prod
    networks:
      - prisma-network


networks:
  prisma-network:

# Определение постоянных томов для хранения данных
volumes:
  postgres_volumes:  # Имя тома для данных PostgreSQL
  # Автоматическое создание тома при первом запуске
